### PR TITLE
US6530 Improve crash logs

### PR DESCRIPTION
**Pull request by DoingItNow**
Create line separator between the user description
and the europa log files

### CODE REVIEW

**Comment by DoingItNow** [comment]
@lurkerbot @rusminsusanto

**Comment by rusminsusanto** [comment]
I am fine with this. What do you think Marten?

**Comment by DarrenFordQSR** [comment]
:+1:

**Comment by dominic-zhang** [comment]
:+1:

**Comment by DoingItNow** [comment]
Had to change a slight issue. When the user doesn't make a description, forgot to add "/" next to n, so it prints out nLog instead of a line separator. It is fixed now so if you can quickly check if you have time that will be great! @lurkerbot @rusminsusanto  @DarrenFordQSR  @dominic-zhang

**Comment by rusminsusanto** [comment]
I think this is ok.
:+1: :+1:

**Pull request merged**
