### PR TITLE
WIP: Update to hockeysdk 4 1 3

### PR DESCRIPTION
**Pull request by HarryWangQSR**
update to hockey sdk 4.1.3 from 3.1 and fixed compile error on xcode 9 (beta 5)

This is now a draft only

### CODE REVIEW

**Comment by rusminsusanto** [comment]
Good stuff.
Maybe you can try to crash NVivo and see how it goes. That's what we did last time when updating hockeyapp.
The easiest way is to create an archive build and then crash NVivo.

**Comment by DarrenFordQSR** [comment]
You can crash NVivo in a number of ways from the debug menu

**Comment by HarryWangQSR** [comment]
I haven't test it yet, I will do it. the other option is to get our current version compiles on xc9

**Comment by HarryWangQSR** [comment]
It seems like the crash log has been logged using either 4.1.3 or our old version 3.1 plus change to compile on xc9 https://rink.hockeyapp.net/manage/apps/352255/app_versions/62/crash_reasons/181997346?type=crashes

**Comment by rusminsusanto** [comment]
From Jinny:
Easiest way to crash:
create an external
at the properties, remove end range value, make it blank
then click done

**Comment by rusminsusanto** [comment]
Or you can try to import PDF in this defect DE7093

**Comment by DarrenFordQSR** [comment]
I think this looks good!

👍

**Comment by HarryWangQSR** [comment]
I'll close this PR and replace it with a new one that upgrades directly to hockeysdk release 5.0, which was not available at the time of this patch. one benefit of hockeysdk release 5.0 is that it compiles on xcode 9 directly without needing our hack (which we did in this patch)

**Pull request closed without merging**
