### PR TITLE
Rebase europa branch of hockeysdk-mac against updated master

### PR DESCRIPTION
**Pull request by lurkerbot**
- the main purpose of this is to allow europa to start using v3.1 of the sdk

@peitschie @rusminsusanto @DarrenFordQSR

### CODE REVIEW

**Comment by rusminsusanto** [comment]
:+1:
I've tested this (integrated with Calypso code) and it's ok as far as I can see. Jinny will do some more tests.

**Comment by rusminsusanto** [comment]
Jinny just told me that this is working OK.
The crash report is submitted correctly.

**Comment by DarrenFordQSR** [comment]
:+1:

**Comment by rusminsusanto** [comment]
Ok to go in :+1::+1:

**Pull request merged**
